### PR TITLE
[Merged by Bors] - Updated code to adhere to ADR018

### PR DESCRIPTION
**Pull request by soenkeliebau**
## Description

This contains a breaking change, since the version that is specified for NiFi now has to include a stackable image version.

Previously the version could be specified as "version: 3.2.1" and the operator simply added the stackable version to this. But going forward we have decided that the image version has to be explictly specified, so it will now have to be "version: 3.2.1-stackable-0.1.0" or similar.

This is in accordance with ADR18 (https://docs.stackable.tech/home/contributor/adr/ADR018-product_image_versioning.html).

This PR also moves the integration tests back to this repository and parameterizes them to test with our currently supported ZooKeeper versions.

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by soenkeliebau** [comment]
I have added migration of the tests to this PR and adapted the tests.

**Comment by razvan** [comment]
Just a reminder that there is also : https://github.com/stackabletech/integration-tests/pull/242 which didn't get copied over here because https://github.com/stackabletech/nifi-operator/pull/265 isn't merged.

**Comment by soenkeliebau** [comment]
I have included https://github.com/stackabletech/integration-tests/pull/242 into this PR.

**Comment by soenkeliebau** [comment]
> I have included [stackabletech/integration-tests#242](https://github.com/stackabletech/integration-tests/pull/242) into this PR.

Which was stupid, because I should have rebased #265 and included them there, I will revert.

**Comment by soenkeliebau** [comment]
bors merge

**Pull request closed without merging**
