### PR TITLE
Added bors configuration file

### PR DESCRIPTION
**Pull request by lfrancke**
## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

### CODE REVIEW

**Comment by lfrancke** [comment]
bors try

**Comment by lfrancke** [comment]
bors try

**Comment by lfrancke** [comment]
bors ping

**Comment by lfrancke** [comment]
bors try

**Comment by lfrancke** [comment]
bors merge

**Review by soenkeliebau — DISMISSED** [review]

**Comment by lfrancke** [comment]
bors merge

**Comment by lfrancke** [comment]
bors merge

**Comment by lfrancke** [comment]
bors merge

**Comment by lfrancke** [comment]
bors try

**Comment by lfrancke** [comment]
bors try

**Comment by teozkr** [comment]
bors try

**Review by teozkr — DISMISSED** [review]
bors r+

**Comment by lfrancke** [comment]
bors try

**Comment by teozkr** [comment]
bors retry

**Comment by teozkr** [comment]
bors cancel

**Comment by teozkr** [comment]
bors try

**Review by teozkr — APPROVED** [review]
bors r+

**Comment by teozkr** [comment]
bors d=@lfrancke

**Pull request closed without merging**
