### PR TITLE
[Merged by Bors] - Use the testing-tools image

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

To increase test speed and stability
Succeeded on gke

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by razvan** [comment]
This was already done here #323

**Comment by sbernauer** [comment]
Good to know! This PR also has some other improvements, so merging it

**Pull request closed without merging**
