### PR TITLE
docs(getting-started): update stackablectl op install output

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
```[tasklist]
### Run getting_started.sh via
- [x] `stackablectl`
- [x] `helm`
```

### CODE REVIEW

**Comment by NickLarsenNZ** [comment]
Had some trouble when running the `stackablectl` variant. It might have been a transient issue, and the output wasn't very clear other than:

```
Checking if NiFi cluster is ready ... not ready yet!
Retrying in 10 seconds...
Checking if NiFi cluster is ready ... yes
Checking if NiFi cluster has 1 nodes ... jq: parse error: Invalid numeric literal at line 1, column 13
```

**Comment by NickLarsenNZ** [comment]
Another time it wasn't done within 15 iterations of the loop:

```
Checking if NiFi cluster is ready ... not ready yet!
Retrying in 10 seconds...
Could not verify that NiFi cluster works correctly. Setup failed!
```

**Comment by NickLarsenNZ** [comment]
Long story short:
- Getting started guide (sourced from sections of the script) created a single replica. https://github.com/stackabletech/nifi-operator/blob/be555e0858a5354b4574ca69174e537a258ead49/docs/modules/nifi/examples/getting_started/getting_started.sh#L158
- The test-nifi.sh script was checking for a single replica. https://github.com/stackabletech/nifi-operator/blob/be555e0858a5354b4574ca69174e537a258ead49/docs/modules/nifi/examples/getting_started/test-nifi.sh#L26
- The getting_started.sh.j2 template had been updated long ago to check for 2 replicas. https://github.com/stackabletech/nifi-operator/blob/be555e0858a5354b4574ca69174e537a258ead49/docs/modules/nifi/examples/getting_started/getting_started.sh.j2#L158
- I then rendered the getting_started.sh script from the j2 template which caused it to create 2 replicas. https://github.com/stackabletech/nifi-operator/blob/29dfeb173fc6908ddfdba2543c7f0a83ee7a4489/docs/modules/nifi/examples/getting_started/getting_started.sh#L172

**Review by Techassi — DISMISSED** [review]

**Comment by NickLarsenNZ** [comment]
Actually I want to change the replicas back down to 1, as was done more recently in this PR: https://github.com/stackabletech/nifi-operator/pull/591

The template was the file that was out of date.

I'll rerun the tests with a single node before merging this.

**Comment by NickLarsenNZ** [comment]
The reporter task errors with (single replicas):

```
Exception: Failed to retrieve ReportingTask[StackablePrometheusReportingTask/8081]: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 22 Jul 2024 11:58:20 GMT', 'Set-Cookie': '__Secure-Request-Token=e01f6882-a956-430a-906f-6e6f981bdf39; Path=/; Domain=simple-nifi-reporting-task.default.svc.cluster.local; Secure; SameSite=Strict', 'Content-Type': 'text/plain', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Content-Security-Policy': "frame-ancestors 'self'", 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'Content-Length': '66'})
HTTP response body: The Flow Controller is initializing the Data Flow.

Successfully authenticated and established connection with [https://simple-nifi-reporting-task.default.svc.cluster.local:8443/nifi-api]
Stream closed EOF for default/simple-nifi-create-reporting-task-1-27-0-zfw24 (reporting-task)
```

**Comment by NickLarsenNZ** [comment]
Added improved progress output:

image

**Comment by NickLarsenNZ** [comment]
It seems that the test script finishes prematurely. It marks the test as a success even though the reporting task is still crash looping (from when nifi was unavailable). It eventually runs successfully, but we probably need to add some condition to wait for the job to succeed.

**Review by Techassi — APPROVED** [review]

**Pull request merged**
